--- 
abstract: let people finger your git server for... some reason
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.000
license: perl
name: Git-Fingerd
requires: 
  List::Util: 0
  Net::Finger::Server: 0.003
  SUPER: 0
  String::Truncate: 0
  Text::Table: 0
version: 1.000
